src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Enable_Pricing_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Pricing Payment</label>
        <type>Checkbox</type>
    </fields>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_RSVP__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Event_RSVPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>7S Event RSVP</label>
    <nameField>
        <label>Event RSVP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Event RSVPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TU_FormAssemblyCompletionController.cls
/**
 * Copyright (c) 2018. 7Summits Inc.
 * Created by Kaj Petersen, 7Summits on 4/27/18.
 */

public with sharing class TU_FormAssemblyCompletionController {

    @AuraEnabled
    public static String getRSVPNextStep(String rsvpId, String eventProductsURL, String eventURL, String errorURL) {

        try {
            List<Event_RSVP__c> rsvpList = new List<Event_RSVP__c>([
                    SELECT Id, Event__c, FAComplete_TU__c, RSVPToken_TU__c,
                            Event__r.Enable_Pricing_Payment__c, Response__c, ParentRSVP_TU__c,
                            Event__r.AssociatedProductCode_TU__c
                    FROM Event_RSVP__c
                    WHERE Id = :rsvpId OR ParentRSVP_TU__c = :rsvpId ORDER BY ParentRSVP_TU__c
            ]);

            Event_RSVP__c thisEventRSVP = rsvpList[0];
            if (!thisEventRSVP.Event__r.Enable_Pricing_Payment__c ||
                    thisEventRSVP.Response__c == TU_EventRSVPHelper.rsvpWaitlist) {
                return eventUrl + thisEventRSVP.Event__c + '?token=' + thisEventRSVP.RSVPToken_TU__c;
            } else {
                return eventProductsURL + '?token=' + thisEventRSVP.RSVPToken_TU__c;
            }

        } catch (Exception e) {
            return errorURL;
        }

    }
}