src/objects/SS_Product_Settings__mdt.object
<CustomObject>
    <description>7Summits Product Catalog component settings</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <description>Default account ID for internal users</description>
        <inlineHelpText>Set a default account ID for internal users</inlineHelpText>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hide_Add_to_Cart__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hide product add to cart button</description>
        <inlineHelpText>Check to hide the Add to Cart button in the product catalog.</inlineHelpText>
        <label>Hide Add to Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Images__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hide product images</description>
        <inlineHelpText>Check to hide all image in the product catalog</inlineHelpText>
        <label>Hide Images</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Unit_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hide product unit price</description>
        <inlineHelpText>Check to hide the product unit price</inlineHelpText>
        <label>Hide Unit Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pricebook_Id__c</fullName>
        <description>Pricebook ID to use for the product catalog</description>
        <inlineHelpText>Enter the price book ID to use for the product catalog</inlineHelpText>
        <label>Pricebook Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_List_IDs__c</fullName>
        <description>List of product IDs to use for product family tile view.</description>
        <inlineHelpText>List of product IDs to use for product family tile view images.</inlineHelpText>
        <label>Product Family List IDs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_List__c</fullName>
        <defaultValue>&quot;1,2,3,4,5,6,7,8,9,10,15,20,30,50&quot;</defaultValue>
        <description>Quantity option list</description>
        <inlineHelpText>CSV list of quantity options</inlineHelpText>
        <label>Quantity List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suggest_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send contact an email when suggesting a product - default is unchecked</description>
        <inlineHelpText>Send an email to a contact when suggesting a product - uncheck for sanbox</inlineHelpText>
        <label>Suggest Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Points__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Points rather than Currency when this is checked</description>
        <inlineHelpText>Check to enable points rather than currency for product.</inlineHelpText>
        <label>Use Points</label>
        <type>Checkbox</type>
    </fields>
    <label>SS Product Setting</label>
    <pluralLabel>SS Product Settings</pluralLabel>
</CustomObject>

src/classes/ss_settings.cls
/*
 * Copyright (c) 2017. 7Summits inc.
 */

/**
 * Created by francois korb on 7/18/17.
 */

public with sharing class ss_settings {

	static final String FIELD_SEPARATOR   = ',';
	static final String QUANTITY_DEFAULTS = '1,2,3,4,5,6,7,8,9,10,20,30,50,100';

	@AuraEnabled
	public Boolean hideAddToCart {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean hideImages {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean hideUnitPrice {
		get;
		set;
	}

	@AuraEnabled
	public Boolean usePoints {
		get;
		private set;
	}

	@AuraEnabled
	public String pricebookId {
		get;
		private set;
	}

	@AuraEnabled
	public String accountId {
		get;
		private set;
	}

	@AuraEnabled
	public Boolean suggestEmail {
		get;
		private set;
	}

	@AuraEnabled
	public List<String> familyIds {
		get;
		private set;
	}

	@AuraEnabled
	public List<String> quantityList {
		get;
		private set;
	}

	private void getCustomSettings() {
		SS_Product_Settings__mdt settings = [
				SELECT
					Account_Id__c,
					Hide_Add_to_Cart__c,
					Hide_Images__c,
					Hide_Unit_Price__c,
					Pricebook_Id__c,
					Product_Family_List_IDs__c,
					Suggest_Email__c,
					Use_Points__c,
					Quantity_List__c
				FROM SS_Product_Settings__mdt
				WHERE DeveloperName = 'Default'
		];

		if (settings != null) {
			this.accountId      = settings.Account_Id__c;
			this.hideAddToCart  = settings.Hide_Add_to_Cart__c;
			this.hideImages     = settings.Hide_Images__c;
			this.hideUnitPrice  = settings.Hide_Unit_Price__c;
			this.pricebookId    = settings.Pricebook_Id__c;
			this.usePoints      = settings.Use_Points__c;
			this.suggestEmail   = settings.Suggest_Email__c;
			this.familyIds      = String.isNotBlank(settings.Product_Family_List_IDs__c) ? settings.Product_Family_List_IDs__c.split(FIELD_SEPARATOR) : new List<String>();
			this.quantityList   = String.isNotBlank(settings.Quantity_List__c) ? settings.Quantity_List__c.split(FIELD_SEPARATOR) : QUANTITY_DEFAULTS.split(FIELD_SEPARATOR);
		}
	}

	public ss_settings() {
		getCustomSettings();
	}

	public ss_settings(String accountId, Boolean usePoints, String priceBookId) {
		this.accountId      = accountId;
		this.hideAddToCart  = false;
		this.hideImages     = false;
		this.hideUnitPrice  = false;
		this.pricebookId    = priceBookId;
		this.usePoints      = usePoints;
		this.suggestEmail   = false;
		this.familyIds      = null;
		this.quantityList   = null;
	}
}